#!/usr/bin/env node
/**
 * sweden/engine/build-tokens.js
 * CLI wrapper around the web-css adapter.
 * Reads brand/tokens/source/*.tokens.json → brand/tokens/output/web/*.css
 * Also regenerates showcase/public/colors_and_type.css (flat barrel for Vercel),
 * brand/tokens/output/web-flat/tokens.json, and brand/tokens/output/email/inline.css.
 *
 * Usage:
 *   node sweden/engine/build-tokens.js
 *   node sweden/engine/build-tokens.js --file color-primitives
 *
 * Exports:
 *   buildPublicCss() — regenerate the flat public CSS barrel from canonical token files.
 *   Imported by sync-figma-to-repo.js after patching token CSS files.
 */

'use strict';

const fs      = require('fs');
const path    = require('path');
const adapter = require('../adapters/web-css/index.js');

const ROOT       = path.resolve(__dirname, '../..');
const SOURCE_DIR = path.join(ROOT, 'brand', 'tokens', 'source');
const OUTPUT_DIR = path.join(ROOT, 'brand', 'tokens', 'output', 'web');
const PUBLIC_CSS = path.join(ROOT, 'showcase', 'public', 'colors_and_type.css');

// ── Flat public CSS ───────────────────────────────────────────────────────────
// showcase/public/colors_and_type.css is the Vercel-served barrel — all token
// layers + utility CSS inlined so preview cards and /legacy/ have no import
// chain dependencies. Reads from brand/tokens/output/web/ (web-css adapter
// output) so the barrel is always fresh after run-adapters.js runs.

const TOKEN_FILES = [
  path.join(ROOT, 'brand', 'tokens', 'output', 'web', 'color-primitives.css'),
  path.join(ROOT, 'brand', 'tokens', 'output', 'web', 'color-semantic.css'),
  path.join(ROOT, 'brand', 'tokens', 'output', 'web', 'typography.css'),
  path.join(ROOT, 'brand', 'tokens', 'output', 'web', 'spacing.css'),
  path.join(ROOT, 'brand', 'tokens', 'output', 'web', 'motion.css'),
];

const STYLE_FILES = [
  path.join(ROOT, 'showcase', 'styles', 'typography-utilities.css'),
  path.join(ROOT, 'showcase', 'styles', 'icon-utilities.css'),
  path.join(ROOT, 'showcase', 'styles', 'layout-utilities.css'),
  path.join(ROOT, 'showcase', 'styles', 'components.css'),
];

function buildPublicCss() {
  const sections = [];

  sections.push(
    '/* ============================================================\n' +
    '   Design Token Barrel (flat, generated by build-tokens.js)\n' +
    '   All layers inlined — no @import chains.\n' +
    '   Served at /colors_and_type.css by Vercel for /preview/ and /legacy/.\n' +
    '   DO NOT HAND-EDIT — run: node sweden/engine/build-tokens.js\n' +
    '   ============================================================ */'
  );

  for (const file of TOKEN_FILES) {
    if (!fs.existsSync(file)) continue;
    sections.push(fs.readFileSync(file, 'utf8'));
  }

  for (const file of STYLE_FILES) {
    if (!fs.existsSync(file)) continue;
    let css = fs.readFileSync(file, 'utf8');
    // Fix @font-face src paths relative to showcase/styles/ → relative to /
    css = css.replace(/\.\.\/\.\.\/brand\/fonts\//g, './fonts/');
    sections.push(css);
  }

  const output = sections.join('\n\n') + '\n';
  const publicDir = path.dirname(PUBLIC_CSS);
  if (!fs.existsSync(publicDir)) fs.mkdirSync(publicDir, { recursive: true });
  fs.writeFileSync(PUBLIC_CSS, output, 'utf8');
  console.log(`✓ Wrote showcase/public/colors_and_type.css (flat barrel)`);
}

module.exports = { buildPublicCss };

// ── CLI entry point ───────────────────────────────────────────────────────────

if (require.main === module) {
  const fileFlag = process.argv.slice(2)
    .find(a => a.startsWith('--file=') || !a.startsWith('--'))
    ?.replace('--file=', '');

  const result  = adapter.run(SOURCE_DIR, OUTPUT_DIR, { file: fileFlag });
  const files   = result.files ?? result;
  const written = result.written ?? files.length;
  for (const r of files) {
    console.log(`✓ ${path.relative(ROOT, r.file)}`);
  }
  console.log(`\n✓ ${written} file(s) written, ${files.length - written} unchanged — brand/tokens/output/web/`);

  buildPublicCss();

  // Regenerate adapters — all now read from brand/tokens/source/*.tokens.json
  const OUTPUT_ROOT = path.join(ROOT, 'brand', 'tokens', 'output');
  const webFlat     = require('../adapters/web-flat-json/index.js');
  const emailInline = require('../adapters/email-inline/index.js');

  const wf = webFlat.run(SOURCE_DIR, path.join(OUTPUT_ROOT, 'web-flat'));
  console.log(`✓ brand/tokens/output/web-flat/tokens.json (${wf.tokenCount} tokens, ${wf.written} written)`);

  const ei = emailInline.run(SOURCE_DIR, path.join(OUTPUT_ROOT, 'email'));
  console.log(`✓ brand/tokens/output/email/inline.css (${ei.tokenCount} tokens, ${ei.written} written)`);
}
